import type { Target } from "./types";

export const DEMO_BUDGET = 15000;

export const DEMO_TARGETS: Target[] = [
  {
    id: "demo-1",
    name: "田中部長",
    relationship: "上司",
    preferences: ["コーヒー好き", "お酒好き"],
    gaveLastYear: true,
    receivedReturn: true,
    memo: "去年のお返しは高級紅茶セット。今年も期待できそう",
    gender: "男性",
    ageGroup: "50代+",
    returnValue: 3000,
    gaveYearBefore: true,
    receivedReturnYearBefore: true,
    emotionalPriority: 3,
    relationshipGoal: "深めたい",
    giriAwareness: "義理と認識される",
  },
  {
    id: "demo-2",
    name: "鈴木さん",
    relationship: "気になる人",
    preferences: ["甘党", "ブランド志向"],
    gaveLastYear: false,
    receivedReturn: false,
    memo: "最近よく話すようになった。距離を縮めたい",
    gender: "男性",
    ageGroup: "20代",
    returnValue: null,
    gaveYearBefore: false,
    receivedReturnYearBefore: false,
    emotionalPriority: 5,
    relationshipGoal: "深めたい",
    giriAwareness: "本命と受け取られる可能性あり",
  },
  {
    id: "demo-3",
    name: "山田さん",
    relationship: "同僚",
    preferences: ["健康志向", "紅茶好き"],
    gaveLastYear: true,
    receivedReturn: true,
    memo: "同じプロジェクトで助けてもらった",
    gender: "男性",
    ageGroup: "30代",
    returnValue: 1500,
    gaveYearBefore: true,
    receivedReturnYearBefore: true,
    emotionalPriority: 3,
    relationshipGoal: "現状維持",
    giriAwareness: "義理と認識される",
  },
  {
    id: "demo-4",
    name: "佐藤くん",
    relationship: "同僚",
    preferences: ["甘党"],
    gaveLastYear: true,
    receivedReturn: false,
    memo: "去年も一昨年もお返しなし。正直やめたい",
    gender: "男性",
    ageGroup: "20代",
    returnValue: null,
    gaveYearBefore: true,
    receivedReturnYearBefore: false,
    emotionalPriority: 1,
    relationshipGoal: "礼儀として",
    giriAwareness: "義理と認識される",
  },
  {
    id: "demo-5",
    name: "彼氏",
    relationship: "パートナー",
    preferences: ["お酒好き", "ブランド志向"],
    gaveLastYear: true,
    receivedReturn: true,
    memo: "一番大切な人。ROIは度外視",
    gender: "男性",
    ageGroup: "30代",
    returnValue: 5000,
    gaveYearBefore: true,
    receivedReturnYearBefore: true,
    emotionalPriority: 5,
    relationshipGoal: "深めたい",
    giriAwareness: "不明",
  },
];
